version: '3.7'

services: 
    app:
        build: 
            context: .
        volumes: 
            - static_data:/vol/web
        environment: 
            - SECRET-KEY=samplesecretkey123 #use an .env file to define keys so no one has acces to the key! 
            - ALLOWED_HOSTS=127.0.0.1,localhost #in .env file, customize public ip adresses or public hosts names
    
    proxy:
        build:
            context:  ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on: 
            - app
            
volumes: 
    static_data: